Hw8 notification
azdrachak/OtusAndroid pull request #8
Opened 2020-08-06 10:25 UTC by azdrachak

Установка уведомления посмтреть позже для фильма.
Переход на фильм по клику на уведомление

2020-08-11 14:41 UTC, baidala requested changes
Общие концепции работы с уведомлениями выполнены правильно. есть неточности в реализации

2020-08-11 14:41 UTC, baidala commented on app/src/main/java/com/github/azdrachak/otusandroid/App.kt
>          const val API_KEY = "3e5a35776c3a22fa052f2038c3f87db3"
рекомендовал бы вынести переменные для работы с сетью в отдельный класс
object NetworkConstants в .retrofit и добавить сюда все константы для сетевых запросов.

2020-08-11 14:41 UTC, baidala commented on app/src/main/java/com/github/azdrachak/otusandroid/view/Repository.kt
>      fun addMovies(movies: List<MovieItem>) {
рекомендую добавление делать в транзакции:
db?.runInTransaction( ()->{
     removeAllMovies()
     addMovies(moviesList)
})
изменения не будут доступны пока не выполнятся все операции в транзакции. если будет ошибка - сохранятся старые данные.

2020-08-11 14:41 UTC, baidala commented on app/src/main/java/com/github/azdrachak/otusandroid/view/MainActivity.kt
> +            notificationManager.createNotificationChannel(notificationChannel)
notificationManager?.createNotificationChannel(notificationChannel)

2020-08-11 14:41 UTC, baidala commented on app/src/main/java/com/github/azdrachak/otusandroid/view/MainActivity.kt
> +        viewModel.alarmViewModel.observe(this, Observer {
alarmViewModel надо переименовать т.к. это liveData - например alarmLiveData.
сообщение "Notification set" сохраняется в очереди и отображается повторно при перевороте экрана. надо исправить. про это было на лекции по MVVM (Архитектурные компоненты. SingleEvent)

2020-08-11 14:41 UTC, baidala commented on app/src/main/java/com/github/azdrachak/otusandroid/view/DetailsFragment.kt
> +        )
проверьте правильность установки формата времени. у меня на телефоне вместо 17-36 ставится 05-36. и в дальнейшем идет неправильная конвертация в миллисекунды и alarm ставится на совсем другое время. сейчас правильно работает только если ставить в формате 12часов. т.е. на 05-45 срабатывает правильно в 17-45

2020-08-11 15:20 UTC, baidala requested changes
Общие концепции работы с уведомлениями выполнены правильно. есть неточности в реализации

2020-08-12 07:06 UTC, baidala commented on app/src/main/java/com/github/azdrachak/otusandroid/view/MainActivity.kt
> +                set(Calendar.HOUR, it.hour)
Calendar.HOUR_OF_DAY

2020-08-12 09:30 UTC, azdrachak commented on app/src/main/java/com/github/azdrachak/otusandroid/view/Repository.kt
>      fun addMovies(movies: List<MovieItem>) {
Фильмы независимы ведь друг от друга, если не запишется какой-то, а остальные отработают, то это не критично кмк. А запись тут происходит каждого отдельно с учетом его статуса favorite

2020-08-12 09:31 UTC, azdrachak commented on app/src/main/java/com/github/azdrachak/otusandroid/App.kt
>          const val API_KEY = "3e5a35776c3a22fa052f2038c3f87db3"
принято

2020-08-12 09:32 UTC, azdrachak commented on app/src/main/java/com/github/azdrachak/otusandroid/view/MainActivity.kt
> +        viewModel.alarmViewModel.observe(this, Observer {
Да, по инерции написал viewModel =)

2020-08-12 09:33 UTC, azdrachak commented on app/src/main/java/com/github/azdrachak/otusandroid/view/DetailsFragment.kt
> +        )
Принято

2020-08-12 11:30 UTC, baidala approved these changes
задание принято

2020-08-12 11:30 UTC, baidala commented on app/src/main/java/com/github/azdrachak/otusandroid/view/MovieItemViewHolder.kt
> +        month = calendar.toZonedDateTime().monthValue - 1 // месяц считается с 0?
zonedDateTime вернет  8.
но DatePickerDialog ожидает месяц с 0. по этому нужно делать -1.
https://stackoverflow.com/questions/7182996/java-get-month-integer-from-date
zonedDateTime в доке написано
/**
     * Gets the month-of-year field from 1 to 12.
     * This method returns the month as an {@code int} from 1 to 12.
     * Application code is frequently clearer if the enum {@link Month}
     * is used by calling {@link #getMonth()}.
     *
     * @return the month-of-year, from 1 to 12
     * @see #getMonth()
     */

2020-08-12 11:30 UTC, baidala commented on app/src/main/java/com/github/azdrachak/otusandroid/view/MovieItemViewHolder.kt
> +            DatePickerDialog(movieView.context, this, year, month, day)
month -1 лучше передавать именно в диалог.
month = calendar.toZonedDateTime().monthValue
DatePickerDialog(movieView.context, this, year, month-1, day)
т.к. это именно диалог требует с 0

2020-08-12 12:18 UTC, merged